In [14]:
import pandas as pd
import numpy as np

In [15]:
def fetch_data_df():
    df = pd.read_csv('../../data/asset_classes.csv', index_col=0)
    df.index = pd.to_datetime(df.index)
    df = df.iloc[:, :5]
    return df

In [16]:
df = fetch_data_df()

In [17]:
df

,ACWI.World.Equities,AGGG.World.Debt,AHYG.Asia.Debt,BWX.World.Debt,EDIV.EmergingMarkets.Equities
Exchange Date,,,,,
2024-10-10,119.41,4.3990,6.70,22.500,37.05
2024-10-09,119.53,4.3965,6.68,22.515,36.94
2024-10-08,119.04,4.4055,6.68,22.655,37.21
2024-10-07,118.73,4.4050,6.69,22.655,37.96
2024-10-04,119.48,4.4075,6.69,22.700,37.56
...,...,...,...,...,...
2012-01-16,NaN,NaN,NaN,NaN,NaN
2012-01-13,42.82,NaN,NaN,NaN,48.10
2012-01-12,43.17,NaN,9.98,NaN,48.57
2012-01-11,43.15,NaN,NaN,NaN,48.23
2012-01-10,43.00,NaN,NaN,NaN,48.18

In [18]:
df.shape

(3309, 5)

In [19]:
returns_df = df.pct_change(fill_method=None).dropna()
returns_df

,ACWI.World.Equities,AGGG.World.Debt,AHYG.Asia.Debt,BWX.World.Debt,EDIV.EmergingMarkets.Equities
Exchange Date,,,,,
2024-10-09,0.001005,-0.000568,-0.002985,0.000667,-0.002969
2024-10-08,-0.004099,0.002047,0.000000,0.006218,0.007309
2024-10-07,-0.002604,-0.000113,0.001497,0.000000,0.020156
2024-10-04,0.006317,0.000568,0.000000,0.001986,-0.010537
2024-10-03,-0.008370,0.011685,0.000000,0.007930,0.000000
...,...,...,...,...,...
2018-05-09,-0.010064,-0.000803,-0.003902,-0.004231,-0.015822
2018-05-08,-0.005770,0.000201,0.008815,0.000000,0.001191
2018-05-03,-0.008308,0.001402,-0.001929,0.001758,-0.005443
2018-04-26,-0.002072,-0.001495,-0.002890,-0.001565,-0.002321
2018-04-25,-0.008027,0.000998,0.001932,-0.001045,-0.007851

In [21]:
weights = np.ones(5) / 5
portfolio_returns = np.dot(returns_df, weights)

In [23]:
portfolio_returns.shape

(1273,)